// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Server;

namespace Mediwatch.Server.Migrations.DbContextMediwatchMigrations
{
    [DbContext(typeof(DbContextMediwatch))]
    [Migration("20200603230000_CreateMediwatchDb3")]
    partial class CreateMediwatchDb3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4");

            modelBuilder.Entity("Server.Models.applicant_session", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("confirmed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("formationid")
                        .HasColumnType("INTEGER");

                    b.Property<int>("idFormation")
                        .HasColumnType("INTEGER");

                    b.Property<int>("idUser")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("payed")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.HasIndex("formationid");

                    b.ToTable("applicant_sessions");
                });

            modelBuilder.Entity("Server.Models.compagny", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("compagnyName")
                        .HasColumnType("TEXT");

                    b.Property<string>("countryCode")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Compagny");
                });

            modelBuilder.Entity("Server.Models.formation", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("address")
                        .HasColumnType("TEXT");

                    b.Property<int?>("compagnyid")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("description")
                        .HasColumnType("TEXT");

                    b.Property<string>("formationName")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("formationTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("free")
                        .HasColumnType("INTEGER");

                    b.Property<int>("idCompagny")
                        .HasColumnType("INTEGER");

                    b.Property<string>("talker")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("compagnyid");

                    b.ToTable("Formation");
                });

            modelBuilder.Entity("Server.Models.tag", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("description")
                        .HasColumnType("TEXT");

                    b.Property<int?>("formationid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("tag_name")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("formationid");

                    b.ToTable("tag");
                });

            modelBuilder.Entity("Server.Models.applicant_session", b =>
                {
                    b.HasOne("Server.Models.formation", null)
                        .WithMany("applicantsSessions")
                        .HasForeignKey("formationid");
                });

            modelBuilder.Entity("Server.Models.formation", b =>
                {
                    b.HasOne("Server.Models.compagny", null)
                        .WithMany("compagnyFormation")
                        .HasForeignKey("compagnyid");
                });

            modelBuilder.Entity("Server.Models.tag", b =>
                {
                    b.HasOne("Server.Models.formation", null)
                        .WithMany("tagsFormation")
                        .HasForeignKey("formationid");
                });
#pragma warning restore 612, 618
        }
    }
}
