version : "3.0"

services :
  server :
    build:
      context: "." 
      dockerfile : "Server/Dockerfile"
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    volumes: 
      - data:/app/Data
      - media_volume:/app/Ressources/Images
      - factures:/invoice_archive
volumes: 
  data:
  media_volume:
  factures: 